
all : lab1-1, lab1-2, lab1-3, lab1-4, lab1-5, lab1-6

lab1-1: lab1-1.c GL_utilities.c 
	gcc -Wall -DGL_GLEXT_PROTOTYPES lab1-1.c GL_utilities.c MicroGlut.c -std=c99 -lGL -lglut -lX11 -lm -o lab1-1

lab1-2: lab1-2.c GL_utilities.c 
	gcc -Wall -DGL_GLEXT_PROTOTYPES lab1-2.c GL_utilities.c MicroGlut.c -std=c99 -lGL -lglut -lX11 -lm -o lab1-2

lab1-3: lab1-3.c GL_utilities.c 
	gcc -Wall -DGL_GLEXT_PROTOTYPES lab1-3.c GL_utilities.c MicroGlut.c -std=c99 -lGL -lglut -lX11 -lm -o lab1-3

lab1-4: lab1-4.c GL_utilities.c 
	gcc -Wall -DGL_GLEXT_PROTOTYPES lab1-4.c GL_utilities.c MicroGlut.c -std=c99 -lGL -lglut -lX11 -lm -o lab1-4

lab1-5: lab1-5.c GL_utilities.c 
	gcc -Wall -DGL_GLEXT_PROTOTYPES lab1-5.c GL_utilities.c MicroGlut.c -std=c99 -lGL -lglut -lX11 -lm -o lab1-5

lab1-6: lab1-6.c GL_utilities.c 
	gcc -Wall -DGL_GLEXT_PROTOTYPES lab1-6.c GL_utilities.c MicroGlut.c loadobj.c -std=c99 -lGL -lglut -lX11 -lm -o lab1-6



clean :
	rm -f lab1-1
	rm -f lab1-2
	rm -f lab1-3
	rm -f lab1-4
	rm -f lab1-5
	rm -f lab1-6
