
all : lab3-1

lab3-1: lab3-1.c GL_utilities.c 
	gcc  -DGL_GLEXT_PROTOTYPES lab3-1.c loadobj.c LoadTGA.c VectorUtils3.c GL_utilities.c MicroGlut.c -std=c99 -lGL -lglut -lX11 -lm -o lab3-1

lab3-2: lab3-2.c GL_utilities.c 
	gcc  -DGL_GLEXT_PROTOTYPES lab3-2.c loadobj.c LoadTGA.c VectorUtils3.c GL_utilities.c MicroGlut.c -std=c99 -lGL -lglut -lX11 -lm -o lab3-2

lab3-3: lab3-3.c GL_utilities.c 
	gcc  -DGL_GLEXT_PROTOTYPES lab3-3.c loadobj.c LoadTGA.c VectorUtils3.c GL_utilities.c MicroGlut.c -std=c99 -lGL -lglut -lX11 -lm -o lab3-3

lab3-4: lab3-4.c GL_utilities.c 
	gcc  -DGL_GLEXT_PROTOTYPES lab3-4.c loadobj.c LoadTGA.c VectorUtils3.c GL_utilities.c MicroGlut.c -std=c99 -lGL -lglut -lX11 -lm -o lab3-4

lab3-5: lab3-5.c GL_utilities.c 
	gcc  -DGL_GLEXT_PROTOTYPES lab3-5.c loadobj.c LoadTGA.c VectorUtils3.c GL_utilities.c MicroGlut.c -std=c99 -lGL -lglut -lX11 -lm -o lab3-5

clean :
	rm -f lab3-1
	rm -f lab3-2
	rm -f lab3-3
	rm -f lab3-4
	rm -f lab3-5

